import { useState, useRef } from 'react';
import { ArrowRight, Check, CheckCheck, ChevronLeft, ExternalLink, FilePenLine, Pencil, Plus, Send, Sparkles, X } from 'lucide-react';
import { fields, validateProposal, safeUrl } from '../logic/domain.js';
import { Badge, Empty, Field, ScorePanel } from './components.jsx';

export function CreateView({ draft, step, setStep, questions, errors, update, analyze, publish }) {
  const titles = ['Опишите задачу', 'Уточним важные детали', 'Карточка задачи'];
  return <><div className="page-heading"><div><p className="eyebrow">КОНСТРУКТОР ЗАДАЧИ</p><h1>{titles[step]}</h1><p>{step === 0 ? 'Начните с одной фразы. Дополнить детали можно на следующем шаге.' : step === 1 ? 'Отвечайте только на то, что знаете. Остальные поля можно оставить пустыми.' : 'Проверьте сведения и подтвердите публикацию.'}</p></div><span className="step-count">ШАГ 0{step+1} / 03</span></div><ol className="stepper">{['Черновик','AI-уточнения','Карточка и рейтинг'].map((title,index) => <li key={title} className={step >= index ? 'done' : ''}><span>{step > index ? <Check size={14}/> : index+1}</span>{title}</li>)}</ol><div className="editor-layout"><section className="editor panel">
    {step === 0 && <form noValidate onSubmit={(event) => { event.preventDefault(); analyze(); }}><div className="ai-note"><Sparkles size={21}/><div><b>AI-анализ · локальная имитация</b><p>Проверяем полноту описания и подбираем уточняющие вопросы. Данные остаются в браузере.</p></div></div><Field name="rawDescription" label="Что нужно вашему бизнесу?" required value={draft.rawDescription} onChange={(value) => update('rawDescription',value)} multiline rows={7} placeholder="Например: нужно улучшить продажи. Мы не понимаем, почему клиенты перестали возвращаться." error={errors.analysis}/><p className="small-note">Для точного переноса можно писать по строкам: «Контекст: …», «Пользователи: …», «Данные и материалы: …». Неизвестные сведения останутся пустыми.</p><div className="form-actions"><button type="submit" className="primary">Проанализировать <Sparkles size={17}/></button></div>{errors.analysis && draft.rawDescription.trim() && <button type="button" className="text-button" onClick={() => { if (!draft.need) update('need', draft.rawDescription); setStep(2); }}>Заполнить карточку вручную</button>}</form>}
    {step === 1 && <form onSubmit={(event) => { event.preventDefault(); setStep(2); window.scrollTo(0,0); }}><div className="ai-note"><Sparkles size={21}/><div><b>AI-анализ · локальная имитация</b><p>Подготовлено вопросов: {questions.length}. Мы переносим только введённые вами ответы.</p></div></div><details className="source-description"><summary>Исходное описание</summary><p>{draft.rawDescription}</p></details>{questions.map((question,index) => <Field key={question.key} name={question.key} label={`${index+1}. ${question.text}`} value={draft[question.key]} onChange={(value) => update(question.key,value)} placeholder={fields.find(([key]) => key === question.key)?.[2]}/>)}<div className="form-actions spread"><button type="button" className="secondary" onClick={() => setStep(0)}><ChevronLeft size={16}/>Назад</button><button type="submit" className="primary">Сформировать карточку <ArrowRight size={17}/></button></div></form>}
    {step === 2 && <form noValidate onSubmit={(event) => { event.preventDefault(); publish(); }}><div className="section-heading"><FilePenLine size={20}/><div><h2>Сведения о задаче</h2><p>Обязательны название, тема и потребность. Неполную задачу тоже можно опубликовать.</p></div></div><div className="field-grid">{fields.map(([key,label,placeholder]) => <Field key={key} name={key} label={label} placeholder={placeholder} value={draft[key]} onChange={(value) => update(key,value)} error={errors[key]} required={['title','topic','need'].includes(key)} multiline={!['title','topic','contact'].includes(key)}/>)}</div><div className="confirmation-note"><CheckCheck size={18}/><p>Нажимая кнопку, вы подтверждаете введённые сведения. Карточка станет доступна всем командам в этом браузере.</p></div><div className="form-actions spread">{questions.length > 0 && <button type="button" className="secondary" onClick={() => setStep(1)}><ChevronLeft size={16}/>К вопросам</button>}<button className="primary" type="submit">Подтвердить и опубликовать <Send size={17}/></button></div></form>}
  </section><ScorePanel task={draft} preview/></div></>;
}

export function DetailView({ task, teams, onBack, edit, submit }) {
  const proposalRef = useRef(null);
  return <><button className="back-button" onClick={onBack}><ChevronLeft size={16}/>Все задачи</button><div className="page-heading"><div><p className="eyebrow">{task.topic}</p><h1>{task.title}</h1><p>Открытая задача · команды выбирают самостоятельно</p></div></div><div className="editor-layout"><div><article className="panel detail-panel"><div className="detail-actions"><Badge task={task}/><button className="text-button" onClick={edit}><Pencil size={15}/>Редактировать как бизнес</button></div><div className="detail-fields">{fields.filter(([key]) => !['title','topic'].includes(key)).map(([key,label]) => <section key={key}><h2>{label}</h2><p className={!task[key].trim() ? 'not-provided' : ''}>{task[key].trim() || 'Пока не указано — можно уточнить у бизнеса.'}</p></section>)}</div><button className="primary" onClick={() => { proposalRef.current?.scrollIntoView({ behavior: 'smooth', block: 'start' }); document.getElementById('field-team')?.focus({ preventScroll: true }); }}><Send size={17}/>Откликнуться</button></article><div className="proposal-form panel" ref={proposalRef}><ProposalForm teams={teams} submit={submit}/></div></div><ScorePanel task={task}/></div></>;
}

function ProposalForm({ teams, submit }) {
  const empty = { teamId: '', team: '', idea: '', plan: '', deadline: '', link: '' };
  const [form,setForm] = useState(empty);
  const [errors,setErrors] = useState({});
  const [sent,setSent] = useState(false);
  const update = (key,value) => { setForm((form) => ({ ...form, [key]: value, ...(key === 'team' ? {teamId: ''} : {}) })); setErrors((errors) => ({...errors,[key]: ''})); setSent(false); };
  const send = (event) => {
    event.preventDefault(); const next = validateProposal(form); setErrors(next);
    if (Object.keys(next).length) { document.getElementById(`field-${Object.keys(next)[0]}`)?.focus(); return; }
    submit(form); setForm(empty); setSent(true);
  };
  return <form onSubmit={send} noValidate><div className="section-heading"><Send size={21}/><div><h2>Предложение команды</h2><p>Расскажите, как вы решите задачу. Количество откликов не ограничено.</p></div></div>{sent && <div className="alert success" role="status"><Check size={18}/>Ваш отклик отправлен бизнесу.</div>}<label className="field"><span>Подставить демонстрационный профиль</span><select value={form.teamId} onChange={(event) => { const team = teams.find((team) => team.id === event.target.value); setForm((form) => ({...form, teamId: team?.id || '', team: team?.name || ''})); setErrors((errors) => ({...errors,team:''})); }}><option value="">Своя команда</option>{teams.map((team) => <option key={team.id} value={team.id}>{team.name}</option>)}</select></label>{[['team','Название команды','Например: NeoData'],['idea','Идея решения','Как вы предлагаете решить задачу?'],['plan','План работы','Основные этапы и результат каждого этапа'],['deadline','Срок','Например: 2 недели'],['link','Ссылка на прототип','https://…']].map(([key,label,placeholder]) => <Field key={key} name={key} label={label} value={form[key]} onChange={(value) => update(key,value)} placeholder={placeholder} error={errors[key]} required multiline={['idea','plan'].includes(key)}/>)}<button className="primary" type="submit">Отправить отклик <Send size={17}/></button></form>;
}

const decisions = { new: ['На рассмотрении','pending'], selected: ['Команда выбрана','selected'], declined: ['Отклонено','declined'] };
export function BusinessView({ state, decide, edit, open, start }) {
  const [tab,setTab] = useState('proposals');
  const [taskFilter,setTaskFilter] = useState('all');
  const visible = state.proposals.filter((proposal) => taskFilter === 'all' || proposal.taskId === taskFilter);
  return <><div className="page-heading"><div><p className="eyebrow">РЕШЕНИЕ ЗА ВАМИ</p><h1>Кабинет бизнеса</h1><p>Сравнивайте предложения. Можно выбрать одну, несколько или ни одной команды.</p></div><button className="primary" onClick={start}><Plus size={17}/>Создать задачу</button></div><div className="mode-tabs" aria-label="Раздел кабинета"><button aria-pressed={tab==='proposals'} onClick={() => setTab('proposals')}>Отклики <b>{state.proposals.length}</b></button><button aria-pressed={tab==='tasks'} onClick={() => setTab('tasks')}>Задачи <b>{state.tasks.length}</b></button></div>{tab === 'proposals' ? <><label className="field business-filter"><span>Отклики на задачу</span><select value={taskFilter} onChange={(event) => setTaskFilter(event.target.value)}><option value="all">Все задачи</option>{state.tasks.map((task) => <option key={task.id} value={task.id}>{task.title}</option>)}</select></label><div className="proposal-list">{visible.map((proposal) => {
    const task = state.tasks.find((task) => task.id === proposal.taskId);
    const team = state.teams.find((team) => team.id === proposal.teamId || team.name === proposal.team);
    const [label,tone] = decisions[proposal.status];
    const url = safeUrl(proposal.link);
    return <article className="panel proposal-card" key={proposal.id}><div className="proposal-top"><button className="proposal-task" onClick={() => open(task.id)}>{task.title}<ArrowRight size={14}/></button><span className={`decision ${tone}`}>{label}</span></div><div className="team-heading"><span className="avatar">{proposal.team.slice(0,2).toUpperCase()}</span><div><h2>{proposal.team}</h2>{team && <p>{team.technologies.join(' · ')}</p>}</div></div><div className="proposal-content"><section><h3>Идея решения</h3><p>{proposal.idea}</p></section><section><h3>План</h3><p>{proposal.plan}</p></section></div><div className="proposal-meta"><span>Срок: <b>{proposal.deadline}</b></span>{url ? <a href={url} target="_blank" rel="noopener noreferrer">{url.startsWith('https://example.com/') ? 'Демо-ссылка на прототип' : 'Открыть прототип'}<ExternalLink size={14}/></a> : <span>Ссылка не указана или требует уточнения</span>}</div><div className="proposal-decisions"><span>Ручное решение бизнеса</span><button className="secondary" disabled={proposal.status === 'declined'} onClick={() => decide(proposal.id,'declined')}><X size={16}/>Отклонить</button><button className="primary" disabled={proposal.status === 'selected'} onClick={() => decide(proposal.id,'selected')}><Check size={17}/>Выбрать</button></div></article>;
  })}</div>{!visible.length && <Empty title="Откликов пока нет" text="Команды увидят опубликованную задачу в каталоге и смогут предложить решение."/>}</> : <div className="business-tasks">{state.tasks.map((task) => <article className="panel business-task" key={task.id}><div><span className="topic">{task.topic} · {task.published ? 'Опубликована' : 'Не опубликована'}</span><h2>{task.title}</h2><Badge task={task}/></div><button className="secondary" onClick={() => edit(task)}><Pencil size={16}/>Дополнить задачу</button></article>)}</div>}</>;
}

export function TeamsView({ teams }) {
  return <><div className="page-heading"><div><p className="eyebrow">КОМАНДЫ С РАЗНЫМИ СИЛЬНЫМИ СТОРОНАМИ</p><h1>Профили команд</h1><p>Демонстрационные профили. Команды сами выбирают задачи и отправляют предложения.</p></div></div><div className="team-grid">{teams.map((team,index) => <article className="panel team-card" key={team.id}><div className="team-heading"><span className={`avatar color-${index%3}`}>{team.name.slice(0,2).toUpperCase()}</span><h2>{team.name}</h2></div><h3>Интересы</h3><p>{team.interests.join(' · ')}</p><h3>Навыки</h3><p>{team.skills.join(' · ')}</p><div className="tech-tags">{team.technologies.map((tech) => <span key={tech}>{tech}</span>)}</div></article>)}</div></>;
}
